# Generated by Django 5.2.1 on 2025-05-17 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_document_documenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborations', to=settings.AUTH_USER_MODEL, verbose_name='Соавторы'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Документ заблокирован'),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки'),
        ),
        migrations.AddField(
            model_name='document',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_documents', to=settings.AUTH_USER_MODEL, verbose_name='Заблокирован пользователем'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='content_after',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое после изменения'),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='content_before',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое до изменения'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True, verbose_name='Приватный ключ (зашифрованный)'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('content', models.TextField(verbose_name='Содержимое версии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, max_length=64, verbose_name='Хэш версии')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='users.document')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
