# Generated by Django 5.2.1 on 2025-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_document_is_incoming_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
