# Generated by Django 5.2.1 on 2023-05-19 19:22

import django.db.models.deletion
import datetime
from django.conf import settings
from django.db import migrations, models


def generate_document_numbers(apps, schema_editor):
    """
    Функция для заполнения номеров документов для существующих записей
    """
    Document = apps.get_model('users', 'Document')
    for doc in Document.objects.all():
        if not doc.document_number:
            year = doc.created_at.year
            # Получаем последний документ с номером
            last_doc = Document.objects.filter(
                document_number__startswith=f"{year}-"
            ).order_by('document_number').last()
            
            if last_doc and last_doc.document_number:
                try:
                    # Если есть документ с таким номером, увеличиваем счетчик
                    last_number = int(last_doc.document_number.split('-')[-1])
                    doc.document_number = f"{year}-{last_number + 1:04d}"
                except (ValueError, IndexError):
                    # Если возникла ошибка парсинга номера
                    doc.document_number = f"{year}-0001"
            else:
                # Если это первый документ в году
                doc.document_number = f"{year}-0001"
                
            doc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginhistory_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='addressee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Кому (адресат)'),
        ),
        migrations.AddField(
            model_name='document',
            name='approval_step',
            field=models.IntegerField(default=0, verbose_name='Шаг согласования'),
        ),
        migrations.AddField(
            model_name='document',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='documents_to_approve', to=settings.AUTH_USER_MODEL, verbose_name='Согласовывающие'),
        ),
        migrations.AddField(
            model_name='document',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Текущий согласовывающий'),
        ),
        migrations.AddField(
            model_name='document',
            name='direct_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_documents', to=settings.AUTH_USER_MODEL, verbose_name='Непосредственный начальник'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_to_sign', to=settings.AUTH_USER_MODEL, verbose_name='Подписант'),
        ),
        migrations.RunPython(generate_document_numbers),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('signed', 'Подписано')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('step_number', models.IntegerField(verbose_name='Порядковый номер шага')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='users.document')),
            ],
            options={
                'verbose_name': 'Согласование документа',
                'verbose_name_plural': 'Согласования документов',
                'ordering': ['document', 'step_number'],
                'unique_together': {('document', 'approver', 'step_number')},
            },
        ),
    ]
